FROM python:3.12-slim


RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH


WORKDIR $HOME/app

COPY --chown=user . $HOME/app


RUN pip install --no-cache-dir --user -r requirements.txt




EXPOSE 7860

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
 

